# Generated by Django 5.0.4 on 2024-04-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Content',
            new_name='content',
        ),
    ]
